### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by AGou-ops** [acouvreur/sablier#207]
**Describe the bug**

Cannot run sablier in k8s cluster.

```bash
│ time="2023-09-22T01:43:59Z" level=warning msg="10.96.0.0 - sablier [22/Sep/2023:01:43:59 +0000] \"GET /api/strategies/dynamic\" 404 0 \"\" \"curl/8.0.1\" (1ms)" clientIP=10.96.0.0 dataLeng │
│ th=0 hostname=sablier latency=1 method=GET path=/api/strategies/dynamic referer= statusCode=404 userAgent=curl/8.0.1                                                                         │
│ panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                      │
│ [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x16c9331]                                                                                                                     │
│                                                                                                                                                                                              │
│ goroutine 140 [running]:                                                                                                                                                                     │
│ github.com/acouvreur/sablier/app/providers.(*KubernetesProvider).Start(0x1b4c5d5?, {0xc000498053, 0x5})                                                                                      │
│     /go/src/sablier/app/providers/kubernetes.go:82 +0x71                                                                                                                                     │
│ github.com/acouvreur/sablier/app/sessions.(*SessionsManager).requestSessionInstance(0xc0000b9180, {0xc000498053, 0x5}, 0x0?)                                                                 │
│     /go/src/sablier/app/sessions/sessions_manager.go:187 +0x530                                                                                                                              │
│ github.com/acouvreur/sablier/app/sessions.(*SessionsManager).RequestSession.func1({0xc000498053, 0x5})                                                                                       │
│     /go/src/sablier/app/sessions/sessions_manager.go:151 +0x77                                                                                                                               │
│ created by github.com/acouvreur/sablier/app/sessions.(*SessionsManager).RequestSession in goroutine 137                                                                                      │
│     /go/src/sablier/app/sessions/sessions_manager.go:149 +0xe5      
```

**Context**
 - Sablier version: v1.4.1-beta.1
 - Provider: k8s v1.25.12
 - Reverse proxy: traefik v2.10.4
 - Sablier running inside a container? run as k8s pod.

**Expected behavior**
no error.

**Comment by romancin** [comment]
Same here :(

**Comment by AGou-ops** [comment]
@romancin It's weird, I think it shouldn't have much to do with the name, right? I didn't use `-` character, but still not working.

**Comment by acouvreur** [comment]
Thanks for bringing this issue, I will be looking into it.

In the meantime, can you share more details on the context ?

Like the specific configurations and the request you do to the API!

Thanks

**Comment by AGou-ops** [comment]
@acouvreur Of course, here is my yaml file.

https://gist.github.com/AGou-ops/e096d9e41a7e0f7d0a4908a1b30d94d3

**Comment by danielheimburg** [comment]
I also seem to have this issue, unfortunately we cannot change our deployment names . Any progress on this?

**Comment by acouvreur** [comment]
I'm quite busy at the moment, the change seems easy to fix though.
If I have the time I'll submit a change to fix this.

However, feel free to contribute! It would be really appreciated!

**Comment by AGou-ops** [comment]
Thank you @acouvreur ,it works now. You can close this issue then.
